---
# tasks file for ansible-role-install-prometheus-node-exporter
- name: "Include role variables"
  include_vars: "main.yml"

- name: "Gather facts"
  setup:    # equivalent to "gather_facts: yes"

- name: "Check is_ubuntu facts"
  include_role:
    name: itnok.is_ubuntu

- name: "Check latest release available of Prometheus Node Exporter"
  uri:
    url: "https://api.github.com/repos/prometheus/node_exporter/releases/{{ '' if install_prometheus == 'latest' else 'tags/' }}{{ install_prometheus }}"
    return_content: yes
  register: latest_node_exporter
  retries: 7
  delay: 15

- name: "Create temporary directory to save SHA256 checksums"
  tempfile:
    state: directory
    prefix: "ansible-prometheus"
    suffix: "{{ install_prometheus }}"
  register: prometheus_temp
  changed_when: false

- name: "Download list of SHA256 checksums for {{ install_prometheus }} release of Prometheus Node Exporter"
  get_url:
    url: "{{ item.browser_download_url }}"
    dest: "{{ prometheus_temp.path }}/node_exporter-sha256sums.txt"
  retries: 7
  delay: 15
  with_items: "{{ latest_node_exporter.json.assets }}"
  changed_when: false
  when:
    - item.name is search("sha256sums")

- name: "Fetch Base64-encoded in-memory version of SHA256 checksum for local consumption"
  slurp:
    path: "{{ prometheus_temp.path }}/node_exporter-sha256sums.txt"
  register: prometheus_sha256sums
  retries: 7
  delay: 15

- name: "Decode Base64-encoded SHA256 checksum string"
  set_fact:
    prometheus_sha256sums_decoded: "{{ prometheus_sha256sums['content'] | b64decode }}"

- name: "Remove temporary directory created to save SHA256 checksums"
  file:
    path: "{{ prometheus_temp.path }}"
    state: absent
  changed_when: false
  when: prometheus_temp.path is defined

- name: "Create download info for {{ install_prometheus }} release of Prometheus Node Exporter"
  set_fact:
    install_prometheus_node_exporter:
      url: "{{ item.browser_download_url }}"
      name: "{{ item.name }}"
  with_items: "{{ latest_node_exporter.json.assets }}"
  when:
    - item.name is search("linux-{{ install_prometheus_arch }}")
    - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: "Add SHA256 checksum for {{ install_prometheus }} release to 'install_prometheus_node_exporter' fact"
  set_fact:
    install_prometheus_node_exporter: "{{ install_prometheus_node_exporter | combine({ 'sha256sum': item.split()[0] }) }}"
  with_items:
    - "{{ prometheus_sha256sums_decoded.splitlines() }}"
  when: item is search(install_prometheus_node_exporter.name)

- name: "Download {{ install_prometheus }} release of Prometheus Node Exporter"
  get_url:
    url: "{{ install_prometheus_node_exporter.url }}"
    dest: "/tmp/{{ install_prometheus_node_exporter.name }}"
    checksum: "sha256:{{ install_prometheus_node_exporter.sha256sum }}"
  retries: 7
  delay: 15

- name: "Create a dedicated system user for Prometheus Node Exporter"
  user:
    name: node_exporter
    shell: /bin/false
    system: yes
    create_home: no
    state: present
  become: yes

- name: "Extract 'node_exporter' from {{ install_prometheus_node_exporter.name }}"
  unarchive:
    src: "/tmp/{{ install_prometheus_node_exporter.name }}"
    dest: /usr/local/bin
    extra_opts:
      - --strip=1
      - --wildcards
      - '*/node_exporter'
    owner: "node_exporter"
    group: "node_exporter"
    remote_src: yes
  become: yes

- name: "Set the systemd service file up for Prometheus Node Exporter"
  ini_file:
    path: "/etc/systemd/system/node_exporter.service"
    create: yes
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: "0644"
    owner: root
    group: root
    no_extra_spaces: yes
    backup: no
    state: present
  with_items:
    - { section: "Unit", option: "Description", value: "Prometheus Node Exporter" }
    - { section: "Unit", option: "Wants", value: "network-online.target" }
    - { section: "Unit", option: "After", value: "network-online.target" }
    - { section: "Service", option: "User", value: "node_exporter" }
    - { section: "Service", option: "Group", value: "node_exporter" }
    - { section: "Service", option: "Type", value: "simple" }
    - { section: "Service", option: "ExecStart", value: "/usr/local/bin/node_exporter" }
    - { section: "Install", option: "WantedBy", value: "multi-user.target" }
  become: yes

- name: "Ensure better spacing between sections in systemd service file"
  lineinfile:
    path: "/etc/systemd/system/node_exporter.service"
    insertafter: '^{{ item.regex }}'
    firstmatch: no
    line: ""
    state: present
  with_items:
    - { regex: "After=.*" }
    - { regex: "ExecStart=.*" }
  become: yes

- name: "Force systemd to reread configuration files for services"
  systemd:
    daemon_reload: yes
  become: yes
  when: not is_ubuntu_inside_container | bool

- name: "Enable and restart systemd service for Prometheus Node Exporter"
  systemd:
    name: "node_exporter"
    enabled: yes
    state: restarted
  become: yes
  when: not is_ubuntu_inside_container | bool
